### ISSUE TITLE
grunt compile fails

### ISSUE THREAD

**Issue by thom4parisot** [kaosf/ti-webview#1]
Any idea? I think I followed the steps properly (unless for grunt-cli I already had installed on my machine).

``` bash
$ grunt compile build
Running "coffee:base" (coffee) task
File app/alloy.js created.
File app/controllers/index.js created.

Running "exec:alloy" (exec) task
       .__  .__
___  |  | |  |   ___ __.__.
\__  \ |  | |  |  /  _ <   |  |
 / _ \|  |_|  |_(  <_> )__  |
(____  /____/____/\____// ____|
     \/                 \/
Alloy by Appcelerator. The MVC app framework for Titanium.

[DEBUG] Cleaning "Resources/alloy/controllers" folder...
[DEBUG] Cleaning "Resources/alloy/models" folder...
[DEBUG] Cleaning "Resources/alloy/widgets" folder...
[DEBUG]
[TRACE]
[DEBUG] ----- BASE RUNTIME FILES -----
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/backbone.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/backbone.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/underscore.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/underscore.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/controllers/BaseController.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/controllers/BaseController.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/sync/localStorage.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/sync/localStorage.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/sync/properties.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/sync/properties.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/sync/sql.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/sync/sql.js
[DEBUG] Copying /Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/lib/alloy/sync/util.js to /Users/thomaspa/Projects/ti-webview/Resources/alloy/sync/util.js
[DEBUG]
[DEBUG] ----- CONFIGURATION -----
[DEBUG] deploytype = development
[DEBUG] beautify = true
[DEBUG] project path = /Users/thomaspa/Projects/ti-webview
[DEBUG] app path = /Users/thomaspa/Projects/ti-webview/app
[DEBUG] platform = undefined
[DEBUG] theme = undefined
[DEBUG]
[DEBUG] ----- MVC GENERATION -----
>> path.js:360
>>         throw new TypeError('Arguments to path.join must be strings');
>>         ^
>> TypeError: Arguments to path.join must be strings
>>     at path.js:360:15
>>     at Array.filter (native)
>>     at Object.exports.join (path.js:358:36)
>>     at loadGlobalStyles (/Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/commands/compile/index.js:571:25)
>>     at module.exports (/Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/commands/compile/index.js:169:2)
>>     at Object.<anonymous> (/Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/Alloy/alloy.js:87:46)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/Users/thomaspa/.nvm/v0.10.25/lib/node_modules/alloy/bin/alloy:3:1)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Function.Module.runMain (module.js:497:10)
>>     at startup (node.js:119:16)
>>     at node.js:902:3
>> Exited with code: 8.
Warning: Task "exec:alloy" failed. Use --force to continue.
```

**Comment by kaosf** [comment]
Thanks for reporting.

Your Node.js version may be 0.10.25, but this project was confirmed with only 0.8.19 (it's too old).

I wasn't maintaining this repository and using Titanium and Alloy for a long time. So I have little knowledge about them now.

**Comment by thom4parisot** [comment]
Oh thanks!

Unfortunately now it's `ti` breaking with node `0.8.19` :-(

``` bash
$ ti

TypeError: Cannot read property '__global__' of undefined
    at /Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/lib/cli.js:256:39
    at cli.parse (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/lib/cli.js:307:3)
    at async.series.results (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:486:21)
    at _asyncMap (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:185:13)
    at async.forEachSeries.iterate (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:108:13)
    at async.forEachSeries (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:184:9)
    at doSeries (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:174:23)
    at async.series (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/node_modules/async/lib/async.js:484:19)
    at Object.<anonymous> (/Users/thomaspa/.nvm/v0.8.19/lib/node_modules/titanium/lib/titanium.js:249:10)
```

**Comment by kaosf** [comment]
Did that error occur before `ti login`?

**Comment by thom4parisot** [comment]
Yep, I tried `ti login` and had the problem. Thus trying with `ti`.

**Comment by kaosf** [comment]
If you can, try to use Node.js with Nodebrew. ...I'm not sure to succeed, but I don't have any more idea X-(
